from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

# Task fields cross a trust boundary: most plans are generated by an LLM and task
# ids are later used in logs and workspace paths.  Keep the accepted vocabulary
# and id grammar in one place so planner and library-created plans are validated
# identically.
TASK_TYPES = frozenset({"research", "code", "write", "analyze"})
TASK_MODES = frozenset({"one_shot", "agentic"})
TASK_DIFFICULTIES = frozenset({"trivial", "easy", "medium", "hard"})
TASK_TOOL_NAMES = frozenset({"run_python", "read_file", "fetch_url"})
MAX_TASK_ID_LENGTH = 64
MAX_GOAL_LENGTH = 1_000_000
_SAFE_TASK_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


class InvalidGoalError(ValueError):
    """A goal is empty, malformed, or too large for Volante's input contract."""


def validate_goal(goal: object) -> str:
    """Return a non-empty goal or raise a stable, machine-classifiable error."""

    if not isinstance(goal, str):
        raise InvalidGoalError("goal must be a string")
    if not goal.strip():
        raise InvalidGoalError("goal must be a non-empty string")
    if len(goal) > MAX_GOAL_LENGTH:
        raise InvalidGoalError(
            f"goal exceeds the {MAX_GOAL_LENGTH}-character safety limit"
        )
    return goal


def validate_task_id(task_id: object) -> str:
    """Return a safe task id or raise ``ValueError``.

    Task ids are intentionally restricted to a short, portable ASCII subset.
    In particular, absolute paths, traversal segments, separators, whitespace,
    control characters, and shell metacharacters are never accepted.
    """

    if not isinstance(task_id, str):
        raise ValueError("task id must be a string")
    if not task_id:
        raise ValueError("task id must not be empty")
    if len(task_id) > MAX_TASK_ID_LENGTH:
        raise ValueError(
            f"task id {task_id!r} exceeds {MAX_TASK_ID_LENGTH} characters"
        )
    if task_id in {".", ".."} or _SAFE_TASK_ID.fullmatch(task_id) is None:
        raise ValueError(
            f"unsafe task id {task_id!r}: use only ASCII letters, digits, '.', '_', "
            "or '-' and start with a letter or digit"
        )
    return task_id


def validate_task(task: Task) -> None:
    """Validate a planner- or caller-created task at the runtime boundary."""

    validate_task_id(task.id)
    if not isinstance(task.description, str) or not task.description.strip():
        raise ValueError(f"task {task.id!r} description must be a non-empty string")
    if task.type not in TASK_TYPES:
        raise ValueError(
            f"task {task.id!r} has invalid type {task.type!r}; "
            f"expected one of {sorted(TASK_TYPES)}"
        )
    if task.mode not in TASK_MODES:
        raise ValueError(
            f"task {task.id!r} has invalid mode {task.mode!r}; "
            f"expected one of {sorted(TASK_MODES)}"
        )
    if task.difficulty not in TASK_DIFFICULTIES:
        raise ValueError(
            f"task {task.id!r} has invalid difficulty {task.difficulty!r}; "
            f"expected one of {sorted(TASK_DIFFICULTIES)}"
        )
    if not isinstance(task.depends_on, list):
        raise ValueError(f"task {task.id!r} depends_on must be a list")
    for dependency in task.depends_on:
        try:
            validate_task_id(dependency)
        except ValueError as exc:
            raise ValueError(
                f"task {task.id!r} has invalid dependency id: {exc}"
            ) from exc
    if not isinstance(task.required_tools, list):
        raise ValueError(f"task {task.id!r} required_tools must be a list")
    if any(not isinstance(tool_name, str) for tool_name in task.required_tools):
        raise ValueError(
            f"task {task.id!r} required_tools must contain only strings"
        )
    if len(task.required_tools) != len(set(task.required_tools)):
        raise ValueError(f"task {task.id!r} required_tools contains duplicates")
    for tool_name in task.required_tools:
        if tool_name not in TASK_TOOL_NAMES:
            raise ValueError(
                f"task {task.id!r} has unsupported required tool {tool_name!r}; "
                f"expected a subset of {sorted(TASK_TOOL_NAMES)}"
            )
    if task.mode == "one_shot" and task.required_tools:
        raise ValueError(
            f"task {task.id!r} is one_shot but declares required_tools"
        )


class CapabilityUnavailableError(RuntimeError):
    """A task requires a capability that no configured model can provide."""


@dataclass
class TextBlock:
    text: str
    type: str = "text"


@dataclass
class ToolUseBlock:
    id: str
    name: str
    input: dict[str, Any]
    type: str = "tool_use"


@dataclass
class ToolResultBlock:
    tool_use_id: str
    content: str
    type: str = "tool_result"


ContentBlock = TextBlock | ToolUseBlock | ToolResultBlock


@dataclass
class CanonicalMessage:
    role: str  # "system" | "user" | "assistant" | "tool"
    content: list[ContentBlock]


def text(role: str, s: str) -> CanonicalMessage:
    return CanonicalMessage(role=role, content=[TextBlock(text=s)])


@dataclass
class ToolSpec:
    name: str
    description: str
    input_schema: dict[str, Any]


@dataclass
class CanonicalRequest:
    messages: list[CanonicalMessage]
    max_tokens: int
    temperature: float = 0.7
    tools: list[ToolSpec] | None = None
    run_id: str = ""
    task_id: str = ""
    attempt: int = 0
    # Optional provider-independent context metadata.  Adapters ignore it; the
    # orchestration layer uses it to keep agentic transcripts within the model
    # actually selected for this request.
    context_window: int | None = None


@dataclass
class Usage:
    prompt_tokens: int
    completion_tokens: int
    estimated: bool = False  # PATCH v2.1: True bila token diestimasi (SDK tak kirim usage)


@dataclass
class CanonicalResponse:
    content: list[ContentBlock]
    usage: Usage
    model: str
    stop_reason: str
    latency_ms: int
    cost_usd: float | None = None  # biaya call otoritatif (total_cost_usd); None jika lain


@dataclass
class ModelInfo:
    id: str  # e.g. "anthropic/claude-opus-4-8"
    provider: str  # "anthropic" | "openai_compat"
    strengths: set[str]  # {"coding","reasoning","long_context","cheap_fast"}
    context_window: int
    max_output_tokens: int
    supports_tools: bool
    cost_per_1k_in: float
    cost_per_1k_out: float
    tier: int = 2  # 1 small … 4 frontier
    billing: str = "card"  # MUST BE LAST: "card" | "plan_credit" | "plan_included"


@dataclass
class Task:
    id: str
    description: str
    type: str  # "research" | "code" | "write" | "analyze"
    mode: str  # "one_shot" | "agentic"
    depends_on: list[str] = field(default_factory=list)
    difficulty: str = "medium"  # trivial|easy|medium|hard
    # Empty on an agentic task is the backward-compatible shorthand for
    # ["run_python"]. New planner output declares the exact tools explicitly.
    required_tools: list[str] = field(default_factory=list)


def effective_required_tools(task: Task) -> frozenset[str]:
    if task.mode != "agentic":
        return frozenset()
    return frozenset(task.required_tools or ["run_python"])


@dataclass
class Entry:
    run_id: str
    task_id: str
    attempt: int
    kind: str  # "artifact" | "fact" | "status"
    payload: Any
    model_id: str | None
    usage: Usage | None
    timestamp: float


@dataclass
class RunResult:
    status: str  # "success" | "failed"
    final: Any | None
    partial_artifacts: dict[str, Any]
    failed_task: str | None
    # PATCH v2.1: close-out akunting (diisi Runtime di KEDUA jalur success & failed)
    usage_total: dict[str, Usage] = field(default_factory=dict)
    cost_usd: float = 0.0
    duration_ms: int = 0
    # Machine-readable close-out detail for structured failures. Existing callers
    # remain source-compatible because both fields are optional.
    error_code: str | None = None
    error_message: str | None = None
    # task_id -> serialized RoutingDecision. Kept provider-agnostic so CLI, UI,
    # MCP, and library callers can explain the choice without importing Router.
    routing_decisions: dict[str, dict[str, Any]] = field(default_factory=dict)
    # Actual physical subscription-provider attempts consumed by this run,
    # including planner, retries, agentic turns, workers, and synthesis.
    subscription_calls: int = 0
    billed_usd: float = 0.0  # cash keluar (card); baca INI utk budget/cap
    credit_usd: float = 0.0  # nilai konsumsi plan_included/plan_credit (bukan cash)
    # True bila ada usage yang DIESTIMASI (provider tak mengirim token count), sehingga
    # cost_usd/billed_usd/credit_usd adalah perkiraan, bukan angka otoritatif. Wajib
    # ditampilkan bersama angka dolar agar klaim "biaya transparan" jujur di titik baca.
    cost_estimated: bool = False
    # Human-readable note about a capability this run did NOT have (currently: code
    # execution withheld, or running unisolated). Surfaced on success AND failure so a
    # caller with no terminal — an IDE MCP client, the Web UI — can tell a full-capability
    # answer from a degraded one instead of silently receiving unexecuted code.
    capability_notice: str | None = None
